server:
  port: 8080
  connection-timeout: 120s
  servlet:
    context-path: /api/morse

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

connector:
  translator:
    baseUrl: http://localhost:3000/morse
